# Site settings
title: Sharing the Tech Love - David H. Wheaton
description: > # this means to ignore newlines until "baseurl:"
  Various things I'm working on, dubiously useful tidbits, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dwheaton.github.io" # the base hostname & protocol for your site
twitter_username: dwheaton
github_username:  dwheaton

# Build settings
markdown: kramdown
